# Generated by Django 5.2.17 on 2026-09-22 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilot_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='charter_app.ship')),
            ],
            options={
                'ordering': ['start_time', 'id'],
                'indexes': [models.Index(fields=['ship', 'start_time', 'end_time'], name='booking_ship_times')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='booking_positive_duration')],
            },
        ),
    ]
