# Generated by Django 5.2.17 on 2026-10-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charter_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='booking_ship_times',
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ship', 'start_time', 'id'], name='booking_ship_start_id'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time', 'id'], name='booking_start_id'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['ship', 'end_time', 'start_time'], name='booking_ship_end_start'),
        ),
    ]
